name: Sync GitHub Actions with Jira

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, edited]

jobs:
  sync_with_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync activity with Jira
        run: |
          function extract_issue_key_from_commit_message {
            echo "$1" | grep -oE 'JIRA-\d+'
          }

          # 예시로 커밋 메시지 사용, 실제 환경에서는 다른 변수 사용 가능
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          JIRA_ISSUE_KEY=$(extract_issue_key_from_commit_message "$COMMIT_MESSAGE")
          
          if [ -z "$JIRA_ISSUE_KEY" ]; then
            echo "No JIRA issue key found in commit message."
            exit 1
          fi

          COMMIT_ID=$(git rev-parse HEAD)
          
          echo "Syncing commit $COMMIT_ID with JIRA issue $JIRA_ISSUE_KEY"
          
          curl -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
               -X POST \
               --data "{\"update\": {\"comment\": [{\"add\": {\"body\": \"Commit '$COMMIT_ID' was added to this issue: $COMMIT_MESSAGE\"}}]}}" \
               -H "Content-Type: application/json" \
               "${{ secrets.JIRA_BASEURL }}/rest/api/2/issue/$JIRA_ISSUE_KEY"
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASEURL: ${{ secrets.JIRA_BASEURL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
