name: Sync GitHub Actions with Jira

on:
  push:
    branches:
      - '*'

jobs:
  sync_with_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Sync commits with Jira
        run: |
          function extract_issue_key_from_commit_message {
            echo "$1" | grep -oE 'JIRA-\d+'
          }

          JIRA_ISSUE_KEY=$(extract_issue_key_from_commit_message "Update create-jira-issue.yml")
          if [ -z "$JIRA_ISSUE_KEY" ]; then
            echo "No JIRA issue key found in commit message."
            exit 1
          fi

          COMMIT_ID="6f2a2640d5fdd55e4fead9548a77940585202111"
          COMMIT_MSG="Update create-jira-issue.yml"
          
          curl -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
               -X POST \
               --data "{\"update\": {\"comment\": [{\"add\": {\"body\": \"Commit '$COMMIT_ID' was added to this issue: $COMMIT_MSG\"}}]}}" \
               -H "Content-Type: application/json" \
               "${{ secrets.JIRA_BASEURL }}/rest/api/2/issue/$JIRA_ISSUE_KEY"
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASEURL: ${{ secrets.JIRA_BASEURL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
