name: Create Jira Issue

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Jira issue
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          curl -D- \
            -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -X POST \
            --data '{
              "fields": {
                "project": {
                  "key": "'"$JIRA_PROJECT_KEY"'"
                },
                "summary": "'"$ISSUE_TITLE"'",
                "description": "'"$ISSUE_BODY"'",
                "issuetype": {
                  "name": "Task"
                }
              }
            }' \
            -H "Content-Type: application/json" \
            "$JIRA_BASE_URL/rest/api/2/issue/"
